export type Category = "nature" | "wildlife" | "city" | "water" | "sky";

export type StreamSource =
  | { type: "youtube"; videoId: string }
  | { type: "windy"; webcamId: string };

export interface Stream {
  id: string;
  videoId: string; // YouTube video ID (kept for backward compat + thumbnails)
  source?: StreamSource; // Optional: if set, used instead of videoId for embed
  location: string;
  description: string;
  category: Category;
  region: string;
  lat?: number;
  lng?: number;
}

export const categories: { key: Category; label: string }[] = [
  { key: "nature", label: "Nature" },
  { key: "wildlife", label: "Wildlife" },
  { key: "city", label: "City" },
  { key: "water", label: "Water" },
  { key: "sky", label: "Sky" },
];

// Curated 24/7 live streams — verified from worldcams.tv, explore.org, EarthCam, Monterey Bay Aquarium, etc.
// Note: YouTube live IDs may rotate when streams restart. Update as needed.
export const streams: Stream[] = [
  // ══════════════════════════════════════
  // ── Nature ──
  // ══════════════════════════════════════
  {
    id: "monterey-jellyfish",
    videoId: "NUnJc82ptd4",
    location: "Monterey Bay, California",
    description: "Jellyfish drifting in silence",
    category: "nature",
    region: "North America",
    lat: 36.62,
    lng: -121.9,
  },
  {
    id: "monterey-moon-jelly",
    videoId: "IeWhbCe2Krk",
    location: "Monterey Bay, California",
    description: "Moon jellies pulsing in blue light",
    category: "nature",
    region: "North America",
    lat: 36.62,
    lng: -121.89,
  },
  {
    id: "niagara-falls",
    videoId: "3KhQK5KG7VU",
    location: "Niagara Falls, Canada",
    description: "Endless water over the edge",
    category: "nature",
    region: "North America",
    lat: 43.08,
    lng: -79.07,
  },
  {
    id: "dolomite-alps",
    videoId: "i01hobM_hGA",
    location: "Tre Cime di Lavaredo, Italy",
    description: "Ancient peaks touching the sky",
    category: "nature",
    region: "Europe",
    lat: 46.62,
    lng: 12.3,
  },
  {
    id: "popocatepetl-volcano",
    videoId: "rayKu7F6Ub4",
    location: "Puebla, Mexico",
    description: "Smoke rising from a sleeping giant",
    category: "nature",
    region: "North America",
    lat: 19.02,
    lng: -98.63,
  },
  {
    id: "iceland-volcano",
    videoId: "4B-xBkUX4jM",
    location: "Reykjanes Peninsula, Iceland",
    description: "Fire breaking through frozen earth",
    category: "nature",
    region: "Europe",
    lat: 63.87,
    lng: -22.41,
  },
  {
    id: "kilauea-volcano",
    videoId: "tk0tfYDxrUA",
    location: "Big Island, Hawaii",
    description: "Lava glowing in the Pacific night",
    category: "nature",
    region: "North America",
    lat: 19.42,
    lng: -155.29,
  },
  {
    id: "lake-como",
    videoId: "d0-a8UJAyvY",
    location: "Lake Como, Italy",
    description: "Alpine waters still as glass",
    category: "nature",
    region: "Europe",
    lat: 46.02,
    lng: 9.26,
  },
  {
    id: "geirangerfjord",
    videoId: "yMSc-qqW3To",
    location: "Geirangerfjord, Norway",
    description: "Fjord walls rising from deep water",
    category: "nature",
    region: "Europe",
    lat: 62.1,
    lng: 7.09,
  },
  {
    id: "etna-volcano",
    videoId: "KB3f4zmkqcM",
    location: "Mount Etna, Sicily",
    description: "Europe's restless volcano at twilight",
    category: "nature",
    region: "Europe",
    lat: 37.75,
    lng: 14.99,
  },

  // ══════════════════════════════════════
  // ── Wildlife ──
  // ══════════════════════════════════════
  {
    id: "chengdu-pandas",
    videoId: "gnEuhfyZPPQ",
    location: "Chengdu, China",
    description: "Giant pandas in bamboo reverie",
    category: "wildlife",
    region: "Asia",
    lat: 30.74,
    lng: 104.15,
  },
  {
    id: "big-bear-eagles",
    videoId: "B4-L2nfGcuE",
    location: "Big Bear Lake, California",
    description: "Bald eagles guarding their nest",
    category: "wildlife",
    region: "North America",
    lat: 34.24,
    lng: -116.89,
  },
  {
    id: "sf-penguins",
    videoId: "DaB_xIJEXzs",
    location: "San Francisco, California",
    description: "African penguins waddling on stone",
    category: "wildlife",
    region: "North America",
    lat: 37.77,
    lng: -122.47,
  },
  {
    id: "cape-town-beach-wildlife",
    videoId: "70gObI9oeVU",
    location: "Muizenberg, Cape Town",
    description: "Waves and wildlife on the cape",
    category: "wildlife",
    region: "Africa",
    lat: -34.11,
    lng: 18.47,
  },

  // ══════════════════════════════════════
  // ── City ── EUROPE
  // ══════════════════════════════════════
  {
    id: "paris-eiffel-tower",
    videoId: "OzYp4NRZlwQ",
    location: "Paris, France",
    description: "Iron lattice glowing over the Seine",
    category: "city",
    region: "Europe",
    lat: 48.86,
    lng: 2.29,
  },
  {
    id: "paris-sacre-coeur",
    videoId: "lNAhqd8JLtw",
    location: "Montmartre, Paris",
    description: "White dome watching over the city",
    category: "city",
    region: "Europe",
    lat: 48.89,
    lng: 2.34,
  },
  {
    id: "london-city-views",
    videoId: "8JCk5M_xrBs",
    location: "London, United Kingdom",
    description: "Rain-washed streets under grey skies",
    category: "city",
    region: "Europe",
    lat: 51.51,
    lng: -0.12,
  },
  {
    id: "venice-grand-canal",
    videoId: "P6JA_YjHMZs",
    location: "Venice, Italy",
    description: "Gondolas gliding through ancient waterways",
    category: "city",
    region: "Europe",
    lat: 45.44,
    lng: 12.33,
  },
  {
    id: "berlin-panorama",
    videoId: "LAJiFSw2ICc",
    location: "Berlin, Germany",
    description: "A city forever rebuilding itself",
    category: "city",
    region: "Europe",
    lat: 52.52,
    lng: 13.41,
  },
  {
    id: "dublin-temple-bar",
    videoId: "3nyPER2kzqk",
    location: "Temple Bar, Dublin",
    description: "Cobblestones and passing strangers",
    category: "city",
    region: "Europe",
    lat: 53.35,
    lng: -6.26,
  },
  {
    id: "jerusalem-western-wall",
    videoId: "UyduhBUpO7Q",
    location: "Jerusalem, Israel",
    description: "Prayers pressed against ancient stone",
    category: "city",
    region: "Middle East",
    lat: 31.78,
    lng: 35.23,
  },

  // ── City ── ASIA
  {
    id: "tokyo-shibuya",
    videoId: "dfVK7ld38Ys",
    location: "Shibuya, Tokyo",
    description: "Crossing lights in the rain",
    category: "city",
    region: "Asia",
    lat: 35.66,
    lng: 139.7,
  },
  {
    id: "tokyo-shinjuku",
    videoId: "Zhmmh7l6KEw",
    location: "Shinjuku, Tokyo",
    description: "Neon rivers flowing through the night",
    category: "city",
    region: "Asia",
    lat: 35.69,
    lng: 139.7,
  },
  {
    id: "tokyo-asakusa",
    videoId: "6dp-bvQ7RWo",
    location: "Asakusa, Tokyo",
    description: "Temple bells and lantern light",
    category: "city",
    region: "Asia",
    lat: 35.71,
    lng: 139.8,
  },
  {
    id: "tokyo-akihabara",
    videoId: "lA6TaaMGgDo",
    location: "Akihabara, Tokyo",
    description: "Electric town buzzing after dark",
    category: "city",
    region: "Asia",
    lat: 35.7,
    lng: 139.77,
  },
  {
    id: "hong-kong-harbor",
    videoId: "4HbCkzDqHEk",
    location: "Victoria Harbour, Hong Kong",
    description: "Skyline reflected on the water",
    category: "city",
    region: "Asia",
    lat: 22.29,
    lng: 114.17,
  },
  {
    id: "singapore-downtown",
    videoId: "q7Oiln7QlDE",
    location: "Marina Bay, Singapore",
    description: "City skyline across still water",
    category: "city",
    region: "Asia",
    lat: 1.28,
    lng: 103.86,
  },
  {
    id: "seoul-banpo-bridge",
    videoId: "-JhoMGoAfFc",
    location: "Seoul, South Korea",
    description: "Rainbow fountain on the Han River",
    category: "city",
    region: "Asia",
    lat: 37.51,
    lng: 126.99,
  },
  {
    id: "seoul-gyeongbokgung",
    videoId: "VBlN0MGqyz4",
    location: "Seoul, South Korea",
    description: "Palace gates standing through centuries",
    category: "city",
    region: "Asia",
    lat: 37.58,
    lng: 126.98,
  },
  {
    id: "bangkok-sukhumvit",
    videoId: "UemFRPrl1hk",
    location: "Bangkok, Thailand",
    description: "Tuk-tuks weaving through golden light",
    category: "city",
    region: "Asia",
    lat: 13.73,
    lng: 100.56,
  },
  {
    id: "taipei-traffic",
    videoId: "pmM2CeSAx0I",
    location: "Taipei, Taiwan",
    description: "Scooter rivers beneath Taipei 101",
    category: "city",
    region: "Asia",
    lat: 25.03,
    lng: 121.57,
  },

  // ── City ── AMERICAS
  {
    id: "nyc-times-square",
    videoId: "rnXIjl_Rzy4",
    location: "Times Square, New York",
    description: "Neon pulse of the city",
    category: "city",
    region: "North America",
    lat: 40.76,
    lng: -73.99,
  },
  {
    id: "nyc-empire-state",
    videoId: "TdGXlEOxuOw",
    location: "Manhattan, New York",
    description: "Empire State standing above the grid",
    category: "city",
    region: "North America",
    lat: 40.75,
    lng: -73.99,
  },
  {
    id: "nyc-brooklyn-bridge",
    videoId: "la90mA4VLa4",
    location: "Brooklyn Bridge, New York",
    description: "Cables stretching between two worlds",
    category: "city",
    region: "North America",
    lat: 40.71,
    lng: -73.99,
  },
  {
    id: "chicago-skyline",
    videoId: "E4dp1EzsJaY",
    location: "Chicago, Illinois",
    description: "Lakefront wind shaping the skyline",
    category: "city",
    region: "North America",
    lat: 41.88,
    lng: -87.62,
  },
  {
    id: "miami-biscayne",
    videoId: "4UzQd1dVPlo",
    location: "Miami, Florida",
    description: "Pastel light on Biscayne Bay",
    category: "city",
    region: "North America",
    lat: 25.77,
    lng: -80.19,
  },
  {
    id: "buenos-aires-obelisk",
    videoId: "rqBfiegG5qU",
    location: "Buenos Aires, Argentina",
    description: "Obelisk rising on the widest avenue",
    category: "city",
    region: "South America",
    lat: -34.6,
    lng: -58.38,
  },
  {
    id: "mexico-city-volcano",
    videoId: "B7jUvXADO1c",
    location: "Mexico City, Mexico",
    description: "Volcano watching over the valley",
    category: "city",
    region: "North America",
    lat: 19.43,
    lng: -99.13,
  },
  {
    id: "toronto-skyline",
    videoId: "dXUzu9XiKwk",
    location: "Toronto, Canada",
    description: "CN Tower piercing low clouds",
    category: "city",
    region: "North America",
    lat: 43.65,
    lng: -79.38,
  },

  // ── City ── AFRICA & OCEANIA
  {
    id: "cape-town-skyline",
    videoId: "4Zu64CmAjMo",
    location: "Cape Town, South Africa",
    description: "Table Mountain under passing clouds",
    category: "city",
    region: "Africa",
    lat: -33.92,
    lng: 18.42,
  },
  {
    id: "auckland-skyline",
    videoId: "Ql7graq0I9M",
    location: "Auckland, New Zealand",
    description: "Harbour city at the edge of the world",
    category: "city",
    region: "Oceania",
    lat: -36.85,
    lng: 174.76,
  },

  // ══════════════════════════════════════
  // ── Water ──
  // ══════════════════════════════════════
  {
    id: "hawaii-beach",
    videoId: "hPvl6IACa2k",
    location: "Maui, Hawaii",
    description: "Pacific swells reaching golden shore",
    category: "water",
    region: "North America",
    lat: 20.73,
    lng: -156.45,
  },
  {
    id: "rio-copacabana",
    videoId: "kxD9qBk6WQ8",
    location: "Copacabana, Rio de Janeiro",
    description: "Waves meeting crescent sand",
    category: "water",
    region: "South America",
    lat: -22.97,
    lng: -43.18,
  },
  {
    id: "sydney-harbor",
    videoId: "5uZa3-RMFos",
    location: "Sydney Harbour, Australia",
    description: "Opera House sails catching the light",
    category: "water",
    region: "Oceania",
    lat: -33.86,
    lng: 151.21,
  },
  {
    id: "san-francisco-bay",
    videoId: "BSWhGNXxT9A",
    location: "San Francisco Bay, California",
    description: "Fog rolling under the Golden Gate",
    category: "water",
    region: "North America",
    lat: 37.83,
    lng: -122.37,
  },
  {
    id: "tokyo-rainbow-bridge",
    videoId: "KR7qSzE1j_w",
    location: "Tokyo Bay, Japan",
    description: "Rainbow Bridge arching over dark water",
    category: "water",
    region: "Asia",
    lat: 35.64,
    lng: 139.76,
  },

  // ══════════════════════════════════════
  // ── Sky ──
  // ══════════════════════════════════════
  {
    id: "iss-earth",
    videoId: "vytmBNhc9ig",
    location: "Low Earth Orbit",
    description: "Earth turning below in silence",
    category: "sky",
    region: "Space",
    lat: 0,
    lng: 0,
  },
  {
    id: "lax-airport",
    videoId: "12KqO5IBLeY",
    location: "Los Angeles, California",
    description: "Planes against the sunset sky",
    category: "sky",
    region: "North America",
    lat: 33.94,
    lng: -118.41,
  },
  {
    id: "sfo-airport",
    videoId: "ThpFcm9vD7c",
    location: "San Francisco, California",
    description: "Runways stretching into the bay",
    category: "sky",
    region: "North America",
    lat: 37.62,
    lng: -122.38,
  },
  {
    id: "zurich-airport",
    videoId: "Qcz9JKxFfW4",
    location: "Zurich, Switzerland",
    description: "Swiss precision on the tarmac",
    category: "sky",
    region: "Europe",
    lat: 47.46,
    lng: 8.55,
  },
  {
    id: "mount-fuji",
    videoId: "SQyTWk7OxSI",
    location: "Fujikawaguchiko, Japan",
    description: "Fuji-san in morning stillness",
    category: "sky",
    region: "Asia",
    lat: 35.36,
    lng: 138.73,
  },
  {
    id: "tokyo-tower-panorama",
    videoId: "VM18f-IIUTw",
    location: "Shimbashi, Tokyo",
    description: "City lights stretching to the horizon",
    category: "sky",
    region: "Asia",
    lat: 35.66,
    lng: 139.75,
  },
  {
    id: "paris-seine-notredame",
    videoId: "k3DZKHJ4Aqg",
    location: "Paris, France",
    description: "Seine flowing past Notre-Dame's rebirth",
    category: "sky",
    region: "Europe",
    lat: 48.85,
    lng: 2.35,
  },
];

export function getStreamsByCategory(category: Category): Stream[] {
  return streams.filter((s) => s.category === category);
}
